[manifest]
version = "1.0.0"
dump_lua = true
priority = 999

[[patches]] # Accomodate pool rates totalling for Cryptid patches
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
total_rate = total_rate + ( G.GAME[v:lower()..'_rate'] * (G.GAME.cry_percrate[v:lower()]/100) )
'''
position = 'at'
payload = '''
if SuperRogue.is_pool_available(v) then
    total_rate = total_rate + ( G.GAME[v:lower()..'_rate'] * (G.GAME.cry_percrate[v:lower()]/100) )
end
'''
match_indent = true
times = 1

[[patches]] # Accomodate pool rates table inserting for Cryptid patches
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
table.insert(rates, { type = v, val = G.GAME[v:lower()..'_rate'] * ((num or 100) / 100) })
'''
position = 'at'
payload = '''
if SuperRogue.is_pool_available(v) then
    table.insert(rates, { type = v, val = G.GAME[v:lower()..'_rate'] * ((num or 100) / 100) })
end
'''
match_indent = true
times = 1