[manifest]
version = "1.0.0"
dump_lua = true
priority = 999

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''
if G.P_CENTERS[_achievement].rarity == "zero_secret" then
'''
position = 'at'
payload = '''
if G.P_CENTERS[_achievement] and G.P_CENTERS[_achievement].rarity == "zero_secret" then
'''
match_indent = true
times = 1