[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Add Mods tab to run info tabs
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
{
    label = localize('b_vouchers'),
    tab_definition_function = G.UIDEF.used_vouchers,
},
'''
position = 'after'
payload = '''
{
    label = localize('b_sr_mods'),
    colour = G.C.GOLD,
    tab_definition_function = G.UIDEF.sr_activated_mods,
},
'''
match_indent = true
times = 1

# allows individual tab buttons to be different colours
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
tab_buttons[#tab_buttons+1] = UIBox_button({id = 'tab_but_'..(v.label or ''), ref_table = v, button = 'change_tab', label = {v.label}, minh = 0.8*args.scale, minw = 2.5*args.scale, col = true, choice = true, scale = args.text_scale, chosen = v.chosen, func = v.func, colour = args.colour, focus_args = {type = 'none'}})
'''
match_indent = true
position = "at"
payload = '''
tab_buttons[#tab_buttons+1] = UIBox_button({id = 'tab_but_'..(v.label or ''), ref_table = v, button = 'change_tab', label = {v.label}, minh = 0.8*args.scale, minw = 2.5*args.scale, col = true, choice = true, scale = args.text_scale, chosen = v.chosen, func = v.func, colour = v.colour or args.colour, focus_args = {type = 'none'}})
'''

# Prevent Debuff loc_vars override
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
elseif self.debuff then
'''
position = 'at'
payload = '''
elseif self.debuff and self.config.center_key ~= 'c_sr_mod_cons' then
'''
match_indent = true
times = 1
